"""
PDF I/O: reading patient report PDFs, writing final recommendation PDFs.
"""
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
import pdfplumber


def extract_text_from_pdf(path: str) -> str:
    text_parts = []
    with pdfplumber.open(path) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text() or ""
            text_parts.append(page_text)
    text = "\n".join(text_parts).strip()
    if not text:
        raise ValueError(
            f"No extractable text found in {path}. If this is a scanned "
            f"image PDF, OCR (e.g. pytesseract) would need to be added."
        )
    return text


SEVERITY_COLORS = {
    "severe": colors.HexColor("#B00020"),
    "major": colors.HexColor("#E08600"),
    "minor": colors.HexColor("#2E7D32"),
}


def generate_recommendation_pdf(output_path: str, patient_id: str, source_file: str,
                                 verdicts, escalations, audit_log):
    """
    verdicts: list of SpecialistVerdict-like dicts {case_id, specialty, resolved, treatment_plan, reasoning}
    escalations: list of EscalatedCase-like dicts {case_id, ailment_type, specialty, severity, reason}
    audit_log: list[str]
    """
    doc = SimpleDocTemplate(output_path, pagesize=letter,
                             topMargin=0.75 * inch, bottomMargin=0.75 * inch,
                             title=f"Treatment Recommendation - {patient_id}",
                             author="Patient Triage System")
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], fontSize=18)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], spaceBefore=14)
    body = styles["BodyText"]
    small = ParagraphStyle("Small", parent=styles["BodyText"], fontSize=8, textColor=colors.grey)

    story = []
    story.append(Paragraph("Treatment Recommendation Report", title_style))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"<b>Patient ID:</b> {patient_id}", body))
    story.append(Paragraph(f"<b>Source report:</b> {source_file}", body))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Specialist Recommendations", h2))
    if not verdicts:
        story.append(Paragraph("No resolved specialist recommendations.", body))
    for v in verdicts:
        specialty = v["specialty"].replace("_", " ").title()
        story.append(Paragraph(f"<b>{specialty}</b> &mdash; Case {v['case_id']}", styles["Heading3"]))
        story.append(Paragraph(f"<b>Treatment plan:</b> {v.get('treatment_plan') or 'N/A'}", body))
        story.append(Paragraph(f"<b>Clinical reasoning:</b> {v.get('reasoning', '')}", body))
        story.append(Spacer(1, 8))

    if escalations:
        story.append(Paragraph("Escalated to Human Physician Review", h2))
        data = [["Case ID", "Ailment", "Specialty", "Severity", "Reason"]]
        for e in escalations:
            data.append([e["case_id"], e["ailment_type"], e["specialty"].replace("_", " ").title(),
                         e["severity"].upper(), e["reason"]])
        t = Table(data, colWidths=[0.7*inch, 1.6*inch, 1.2*inch, 0.8*inch, 2.2*inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#333333")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(t)
        story.append(Spacer(1, 12))

    story.append(Paragraph("Audit Trail (classification / reassessment history)", h2))
    for entry in audit_log:
        story.append(Paragraph(entry, small))

    story.append(Spacer(1, 16))
    story.append(Paragraph(
        "This report was generated by an automated triage prototype and is intended "
        "for clinical decision support only. It does not replace evaluation by a "
        "licensed physician.", small))

    doc.build(story)
